name: Docker Build and Push

# Controls when the action will be run. Triggrs the action on push or pull requests events.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # build job
  build:
    # Type of runner the job will run on
    runs-on: ubuntu-latest

    # A sequence of tasks to be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO_NAME }}/python-cicd-assignment:v1.0.0
