name: Test, Build, Push and Deploy

# Controls when the action will be run. Triggrs the action on push or pull requests events.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER_NAME: python-cicd-assignment-cluster1	
  GKE_CLUSTER_ZONE: us-central1-c
  IMAGE_NAME: python-cicd-assignment
  DEPLOYMENT_NAME: python-cicd-assignment
  CONTAINER_REGISTRY_REPO: python-cicd-assignment-repo

jobs:
  # build job
  build:
    # Type of runner the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # A sequence of tasks to be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests with Pytest
        run: |
          pytest
      
      # Set up gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      
      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker
      
      # Get the GKE credentials so that we can deploy to a cluster
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_CLUSTER_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Build and Publish the Docker image
      - name: Build and Publish Docker Image
        run: |-
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/$PROJECT_ID/$CONTAINER_REGISTRY_REPO/$IMAGE_NAME:$GITHUB_SHA \
            .

      # Set up kustomize
      - name: Set up kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          ./kustomize edit set image us-central1-docker.pkg.dev/PROJECT_ID/CONTAINER_REGISTRY_REPO/IMAGE_NAME:TAG=us-central1-docker.pkg.dev/$PROJECT_ID/$CONTAINER_REGISTRY_REPO/$IMAGE_NAME:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide



      